#!/bin/bash

#################################################################
# TAKNET-PS: Configure SSH for Dual Tailscale + LAN Access
# Manages SSH listeners for TAKNET-PS, Private Tailscale, and LAN
#################################################################

set -e

CONFIG_FILE="/etc/ssh/sshd_config.d/99-tailscale.conf"
TAKNET_PS_TAILNET="tail4d77be.ts.net"

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  SSH Dual Tailscale + LAN Configuration"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Get TAKNET-PS Tailscale IP
echo "→ Detecting TAKNET-PS Tailscale..."
TAKNET_IP=""

if command -v tailscale &> /dev/null; then
    # Check if native tailscale is running
    if tailscale status &> /dev/null; then
        # Get DNS name to verify it's TAKNET-PS tailnet
        DNS_NAME=$(tailscale status --json | jq -r '.Self.DNSName' 2>/dev/null | sed 's/\.$//')
        
        if [[ "$DNS_NAME" == *"$TAKNET_PS_TAILNET" ]]; then
            TAKNET_IP=$(tailscale ip -4 2>/dev/null)
            echo "  ✓ TAKNET-PS: $TAKNET_IP"
            echo "    DNS: $DNS_NAME"
        else
            echo "  ⚠ Tailscale connected but not to TAKNET-PS tailnet"
            echo "    Current: $DNS_NAME"
            echo "    Expected: *.$TAKNET_PS_TAILNET"
        fi
    else
        echo "  ⚠ Native Tailscale not connected"
    fi
else
    echo "  ⚠ Tailscale not installed"
fi

# Get Private Tailscale IP (if container running)
echo ""
echo "→ Detecting Private Tailscale..."
PRIVATE_IP=""

if docker ps --filter "name=tailscale-private" --format "{{.Names}}" | grep -q "tailscale-private"; then
    PRIVATE_IP=$(docker exec tailscale-private tailscale ip -4 2>/dev/null || echo "")
    
    if [ -n "$PRIVATE_IP" ]; then
        PRIVATE_DNS=$(docker exec tailscale-private tailscale status --json 2>/dev/null | jq -r '.Self.DNSName' 2>/dev/null | sed 's/\.$//' || echo "")
        echo "  ✓ Private: $PRIVATE_IP"
        if [ -n "$PRIVATE_DNS" ]; then
            echo "    DNS: $PRIVATE_DNS"
        fi
    else
        echo "  ⚠ Container running but not connected"
    fi
else
    echo "  ⚠ Private Tailscale container not running"
fi

# Get LAN IP
echo ""
echo "→ Detecting LAN interface..."
LAN_IP=$(hostname -I | awk '{print $1}')
echo "  ✓ LAN IP: $LAN_IP"

# Generate SSH configuration
echo ""
echo "→ Generating SSH configuration..."

cat > "$CONFIG_FILE" << EOF
# TAKNET-PS SSH Configuration
# Auto-generated by configure-ssh-dual-tailscale.sh
# Do not edit manually - changes will be overwritten

# Listen on all interfaces (LAN + Tailscale networks)
# This allows:
# - Local LAN access for initial setup
# - TAKNET-PS Tailscale admin access
# - Private Tailscale agency access
# 
# Security: Firewall should block SSH from public internet
ListenAddress 0.0.0.0

EOF

echo "  ✓ Listening on all interfaces (0.0.0.0)"
echo "    This includes:"
if [ -n "$LAN_IP" ]; then
    echo "    - LAN: $LAN_IP"
fi
if [ -n "$TAKNET_IP" ]; then
    echo "    - TAKNET-PS Tailscale: $TAKNET_IP"
fi
if [ -n "$PRIVATE_IP" ]; then
    echo "    - Private Tailscale: $PRIVATE_IP"
fi

# Add security settings
cat >> "$CONFIG_FILE" << EOF

# Security Settings
PasswordAuthentication yes
PubkeyAuthentication yes
PermitRootLogin no
PermitEmptyPasswords no

# Note: Firewall rules should restrict SSH from public internet
# SSH is intended for:
# - LAN access (local network)
# - TAKNET-PS Tailscale network
# - Private Tailscale network (if enabled)
EOF

# Validate configuration
echo ""
echo "→ Validating SSH configuration..."
if sshd -t -f /etc/ssh/sshd_config 2>&1 | grep -i error; then
    echo "  ❌ SSH configuration has errors!"
    exit 1
else
    echo "  ✓ SSH configuration valid"
fi

# Reload SSH
echo ""
echo "→ Reloading SSH service..."
if systemctl reload sshd 2>/dev/null || systemctl reload ssh 2>/dev/null; then
    echo "  ✓ SSH service reloaded"
else
    echo "  ❌ Failed to reload SSH service"
    exit 1
fi

# Summary
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  SSH Access Summary"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

if [ -n "$LAN_IP" ]; then
    echo "✓ LAN Access:       ssh pi@$LAN_IP"
fi

if [ -n "$TAKNET_IP" ]; then
    echo "✓ TAKNET-PS Admin:  ssh pi@$TAKNET_IP"
fi

if [ -n "$PRIVATE_IP" ]; then
    echo "✓ Agency Admin:     ssh pi@$PRIVATE_IP"
fi

echo ""
echo "Note: All admins can connect simultaneously"
echo "⚠️  Ensure firewall blocks SSH from public internet"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
